### ISSUE TITLE
Unit tests failure

### ISSUE THREAD

**Issue by gayashanbc** [leopardslab/nodecloud-legacy#47]
# This is a (Bug Report)

## Additional Data

* ***Operating System***: Windows 8.1 64 bit
* ***Stack Trace***:
```
Error: Cannot find module 'D:\repos\nodecloud\nodecloud\node_modules\grpc\src\node\extension_binary\grpc_node.node'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\node_modules\grpc\src\node\src\grpc_extension.js:38:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\node_modules\grpc\src\node\src\client.js:55:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\node_modules\grpc\src\node\index.js:45:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\node_modules\@google-cloud\common-grpc\src\service.js:27:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\node_modules\@google-cloud\common-grpc\src\operation.js:36:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\node_modules\@google-cloud\common-grpc\src\index.js:26:21)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\node_modules\@google-cloud\bigtable\src\index.js:25:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\node_modules\google-cloud\src\index.js:69:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\lib\core\google\provider.js:1:81)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\lib\core\base-provider.js:3:24)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\lib\core\index.js:1:84)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\lib\index.js:1:76)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\test\compute\ec2.js:4:19)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at D:\repos\nodecloud\nodecloud\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (D:\repos\nodecloud\nodecloud\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (D:\repos\nodecloud\nodecloud\node_modules\mocha\lib\mocha.js:514:10)
    at Object.<anonymous> (D:\repos\nodecloud\nodecloud\node_modules\mocha\bin\_mocha:480:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

* ***Provider Error messages***: 
Cannot find module `'D:\repos\nodecloud\nodecloud\node_modules\grpc\src\node\extension_binary\grpc_node.node'`

**Comment by gayashanbc** [comment]
Travis build which runs when we open a PR shows a different error message than this.

* ***Travis build details***: https://travis-ci.org/cloudlibz/nodecloud/jobs/348862187
* ***Provider Error messages***: 
`TypeError: Cannot read property 'accessKeyId' of null`
* ***Stack Trace***: 
```
    at new AWS (/home/travis/build/cloudlibz/nodecloud/lib/core/aws/provider.js:22:36)
    at Provider.getProvider (/home/travis/build/cloudlibz/nodecloud/lib/core/base-provider.js:20:44)
    at new Provider (/home/travis/build/cloudlibz/nodecloud/lib/core/base-provider.js:12:27)
    at Object.getProvider (/home/travis/build/cloudlibz/nodecloud/lib/core/index.js:9:10)
    at Object.<anonymous> (/home/travis/build/cloudlibz/nodecloud/test/compute/ec2.js:7:25)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/cloudlibz/nodecloud/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/cloudlibz/nodecloud/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/home/travis/build/cloudlibz/nodecloud/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/home/travis/build/cloudlibz/nodecloud/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
```

**Comment by dilantha111** [comment]
Hi @gayashanbc  in my case it worked in node 7.0.0. Failed in node 8.9.3

**Comment by gayashanbc** [comment]
Hi @dilantha111, thanks for the heads-up. Apparently it is working for me as well on Node 7.0, previously I was using Node 9.0.

I think the problem is that several dependencies of the [gRPC](https://github.com/grpc/grpc-node) library is not getting installed properly with the newer versions (after Version 7.0) of NodeJS.
