### ISSUE TITLE
Couldn't run the project on MacOS - Cannot read property 'accessKeyId' of null

### ISSUE THREAD

**Issue by lakindu95** [leopardslab/nodecloud-legacy#58]
# This is a Bug Report 

## Description

For bug reports:
* What went wrong?
When trying to run the project from Mac, the project did not initiate due to following error. Tried to hardcode the credentials in providerJS as well in core folder with the region. But no luck. The same process configured earlier was working well on Linux environment. 

* What did you expect should have happened?
Run the initial project

* What was the config you used?
Created a config.json file in the newly created project with the personal aws credentials

* What stacktrace or error message from your provider did you see?
```
/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud/lib/core/aws/provider.js:22
      !this._AWS.config.credentials.accessKeyId ||
                                   ^
TypeError: Cannot read property 'accessKeyId' of null
    at new AWS (/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud/lib/core/aws/provider.js:22:36)
    at Provider.getProvider (/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud/lib/core/base-provider.js:20:44)
    at new Provider (/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud/lib/core/base-provider.js:12:27)
    at Object.getProvider (/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud/lib/core/index.js:9:10)
    at Object.<anonymous> (/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud-mock/index.js:2:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

* ***Operating System***: MacOS
* ***Stack Trace***: 
```
/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud/lib/core/aws/provider.js:22
      !this._AWS.config.credentials.accessKeyId ||
                                   ^
TypeError: Cannot read property 'accessKeyId' of null
    at new AWS (/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud/lib/core/aws/provider.js:22:36)
    at Provider.getProvider (/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud/lib/core/base-provider.js:20:44)
    at new Provider (/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud/lib/core/base-provider.js:12:27)
    at Object.getProvider (/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud/lib/core/index.js:9:10)
    at Object.<anonymous> (/Users/lakindugunasekara/Desktop/nodecloud-test/nodecloud-mock/index.js:2:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```
* ***Provider Error messages***:` TypeError: Cannot read property 'accessKeyId' of null
`

**Comment by raju249** [comment]
I think this means you need to do `aws configure`.
Can you please try `aws configure` and set accessKeyId and accesSecretKey ?

Thanks

**Comment by lakindu95** [comment]
@raju249 I have configured aws as well. Still didn't work though

**Comment by samaystops4no1** [comment]
@raju249 @lakindu95  On mac os, the aws-sdk tries to load credentials from a file located at ``` ~/.aws/credentials```.  When this file is not present the ```AWS.config.credentials``` becomes null and thus it throws the undefined error.
I have made some changes that check for ```this.AWS.config.credentials``` being null. 

After these changes, if your credentials file is not present you will have to set ```process.env.ncconf``` to the path of your ```config.json```. To do this on mac use this command-
```
export ncconf=<PATH to YOUR CONFIG FILE>
